import type { Metadata } from "next";
import { Lora, Actor, Roboto_Mono } from "next/font/google";
import "./globals.css";

const fontSans = Lora({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Actor({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontMono.variable} ${fontSerif.variable} ${fontSans.variable} h-full antialiased`}
    >
      <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
